export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_RESIDENT_REQUEST = 'REGISTER_RESIDENT_REQUEST'
export const REGISTER_RESIDENT_SUCCESS = 'REGISTER_RESIDENT_SUCCESS'
export const REGISTER_RESIDENT_FAIL = 'REGISTER_RESIDENT_FAIL'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'


export const UPDATE_RESIDENT_REQUEST = 'UPDATE_RESIDENT_REQUEST'
export const UPDATE_RESIDENT_SUCCESS = 'UPDATE_RESIDENT_SUCCESS'
export const UPDATE_RESIDENT_RESET = 'UPDATE_RESIDENT_RESET'
export const UPDATE_RESIDENT_FAIL = 'UPDATE_RESIDENT_FAIL'