export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_RESIDENT_REQUEST = 'REGISTER_RESIDENT_REQUEST'
export const REGISTER_RESIDENT_SUCCESS = 'REGISTER_RESIDENT_SUCCESS'
export const REGISTER_RESIDENT_FAIL = 'REGISTER_RESIDENT_FAIL'

export const LOAD_RESIDENT_REQUEST = 'LOAD_RESIDENT_REQUEST'
export const LOAD_RESIDENT_SUCCESS = 'LOAD_RESIDENT_SUCCESS'
export const LOAD_RESIDENT_FAIL = 'LOAD_RESIDENT_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST'
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS'
export const NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL'

export const ALL_RESIDENTS_REQUEST = 'ALL_RESIDENTS_REQUEST'
export const ALL_RESIDENTS_SUCCESS = 'ALL_RESIDENTS_SUCCESS'
export const ALL_RESIDENTS_FAIL = 'ALL_RESIDENTS_FAIL'

export const UPDATE_RESIDENT_REQUEST = 'UPDATE_RESIDENT_REQUEST'
export const UPDATE_RESIDENT_SUCCESS = 'UPDATE_RESIDENT_SUCCESS'
export const UPDATE_RESIDENT_RESET = 'UPDATE_RESIDENT_RESET'
export const UPDATE_RESIDENT_FAIL = 'UPDATE_RESIDENT_FAIL'

export const RESIDENT_DETAILS_REQUEST = 'RESIDENT_DETAILS_REQUEST'
export const RESIDENT_DETAILS_SUCCESS = 'RESIDENT_DETAILS_SUCCESS'
export const RESIDENT_DETAILS_FAIL = 'RESIDENT_DETAILS_FAIL'

export const DELETE_RESIDENT_REQUEST = 'DELETE_RESIDENT_REQUEST'
export const DELETE_RESIDENT_SUCCESS = 'DELETE_RESIDENT_SUCCESS'
export const DELETE_RESIDENT_RESET = 'DELETE_RESIDENT_RESET'
export const DELETE_RESIDENT_FAIL = 'DELETE_RESIDENT_FAIL'

export const RESIDENT_SALES_REQUEST = 'RESIDENT_SALES_REQUEST'
export const RESIDENT_SALES_SUCCESS = 'RESIDENT_SALES_SUCCESS'
export const RESIDENT_SALES_FAIL = 'RESIDENT_SALES_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'